//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custack
{
    [Serializable]
    public class RobotPoseMsg : Message
    {
        public const string k_RosMessageName = "custack_msgs/RobotPose";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        //  AprilTag ID
        public float x;
        //  投影面座標 -1.0 ~ 1.0
        public float y;
        //  投影面座標 -1.0 ~ 1.0
        public float theta;
        //  回転角 (degree または radian)

        public RobotPoseMsg()
        {
            this.id = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.theta = 0.0f;
        }

        public RobotPoseMsg(int id, float x, float y, float theta)
        {
            this.id = id;
            this.x = x;
            this.y = y;
            this.theta = theta;
        }

        public static RobotPoseMsg Deserialize(MessageDeserializer deserializer) => new RobotPoseMsg(deserializer);

        private RobotPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.theta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.theta);
        }

        public override string ToString()
        {
            return "RobotPoseMsg: " +
            "\nid: " + id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\ntheta: " + theta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
