//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custack
{
    [Serializable]
    public class RobotPoseArrayMsg : Message
    {
        public const string k_RosMessageName = "custack_msgs/RobotPoseArray";
        public override string RosMessageName => k_RosMessageName;

        public RobotPoseMsg[] poses;

        public RobotPoseArrayMsg()
        {
            this.poses = new RobotPoseMsg[0];
        }

        public RobotPoseArrayMsg(RobotPoseMsg[] poses)
        {
            this.poses = poses;
        }

        public static RobotPoseArrayMsg Deserialize(MessageDeserializer deserializer) => new RobotPoseArrayMsg(deserializer);

        private RobotPoseArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.poses, RobotPoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "RobotPoseArrayMsg: " +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
